
-- Netflix Data Analysis - Example SQL Queries
-- Generated by Netflix Data Engineering Pipeline

-- 1. Basic content overview
SELECT 
    type,
    COUNT(*) as content_count,
    ROUND(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM netflix_titles), 2) as percentage
FROM netflix_titles 
GROUP BY type;

-- 2. Top 10 countries by content count
SELECT 
    primary_country,
    COUNT(*) as content_count
FROM netflix_titles 
WHERE primary_country IS NOT NULL
GROUP BY primary_country 
ORDER BY content_count DESC 
LIMIT 10;

-- 3. Content added by year
SELECT 
    date_added_year,
    COUNT(*) as titles_added
FROM netflix_titles 
WHERE date_added_year IS NOT NULL
GROUP BY date_added_year 
ORDER BY date_added_year;

-- 4. Most popular genres
SELECT 
    primary_genre,
    COUNT(*) as title_count
FROM netflix_titles 
WHERE primary_genre IS NOT NULL
GROUP BY primary_genre 
ORDER BY title_count DESC 
LIMIT 15;

-- 5. Average movie duration by decade
SELECT 
    decade,
    AVG(duration_value) as avg_duration_minutes,
    COUNT(*) as movie_count
FROM netflix_titles 
WHERE type = 'Movie' AND decade IS NOT NULL AND duration_value IS NOT NULL
GROUP BY decade 
ORDER BY decade;

-- 6. Content by rating category
SELECT 
    rating_category,
    type,
    COUNT(*) as content_count
FROM netflix_titles 
WHERE rating_category IS NOT NULL
GROUP BY rating_category, type 
ORDER BY rating_category, type;

-- 7. International vs domestic content by year
SELECT 
    date_added_year,
    SUM(CASE WHEN is_international = true THEN 1 ELSE 0 END) as international_content,
    SUM(CASE WHEN is_international = false THEN 1 ELSE 0 END) as domestic_content
FROM netflix_titles 
WHERE date_added_year IS NOT NULL
GROUP BY date_added_year 
ORDER BY date_added_year;

-- 8. Longest and shortest content
SELECT 
    title,
    type,
    duration_value,
    duration_unit,
    release_year
FROM netflix_titles 
WHERE duration_value IS NOT NULL
ORDER BY duration_value DESC 
LIMIT 5;

SELECT 
    title,
    type,
    duration_value,
    duration_unit,
    release_year
FROM netflix_titles 
WHERE duration_value IS NOT NULL AND duration_value > 0
ORDER BY duration_value ASC 
LIMIT 5;

-- 9. Content with most diverse cast/crew
SELECT 
    title,
    type,
    cast_count,
    director_count,
    country_count,
    genre_diversity
FROM netflix_titles 
WHERE cast_count IS NOT NULL
ORDER BY (cast_count + director_count + country_count + genre_diversity) DESC 
LIMIT 10;

-- 10. Recent additions analysis
SELECT 
    title,
    type,
    primary_country,
    primary_genre,
    date_added,
    release_year,
    content_age_when_added
FROM netflix_titles 
WHERE date_added >= '2020-01-01'
ORDER BY date_added DESC 
LIMIT 20;
